server:
  port: 4001
  tomcat:
    max-http-post-size: 8000000
#redis
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
    timeout: 0
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 15Mb
  #thymeleaf
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
#database
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis:
  config-location: classpath:mybatis.xml

#logging:
#  level:
#    root: WARN
#    org:
#      springframework:
#        web: DEBUG
#  path: /log
